sudo: required
services:
  - docker

before_install:
  - docker build -t theprotos/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true theprotos/docker-react npm run test -- --coverage